spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #    defer-datasource-initialization: true
    sql:
      init:
        mode: always
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://java_db:5432/postgres
    hikari:
      auto-commit: false
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: javainuse
server:
  port: '8080'
